server:
  port: 8080
spring:
  application:
    name: refresh-token

  datasource:
    url: jdbc:mysql://localhost:3307/task_manager_db
    username: sakib
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret-key: This_is_my_secret_key_afdjaasdfdsf_adjsfhadjsf_aksdjkfh_akjdfhajdsf_asjdlfhadjkf_ajdfhshaf_adisjfadsjf_alkfdjakdf_asldkjfakdf_adslkfja
  expiration: 1m
  refresh-token-expiration: 3d